# Generated by Django 3.0.8 on 2021-09-03 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_slider',
            fields=[
                ('as_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Aboutslider_desc', models.TextField(max_length=50)),
                ('Aboutslider_link', models.URLField()),
                ('Aboutslider_image', models.ImageField(upload_to='Aboutslider_image')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('don_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=39)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Male', max_length=50)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Other', 'Other')], default='Student', max_length=50)),
                ('purpose', models.TextField(max_length=20)),
                ('Adress', models.CharField(max_length=150)),
                ('query', models.TextField(max_length=100)),
                ('ammount', models.IntegerField()),
                ('don_date', models.DateField()),
                ('order_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('ev_id', models.AutoField(primary_key=True, serialize=False)),
                ('ev_name', models.CharField(max_length=100)),
                ('ev_desc', models.TextField(max_length=100)),
                ('ev_about', models.TextField(max_length=500)),
                ('ev_venue', models.CharField(max_length=100)),
                ('ev_mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=50)),
                ('ev_date', models.DateField()),
                ('ev_time', models.TimeField()),
                ('ev_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Today', 'Today'), ('Completed', 'Completed')], default='Upcoming', max_length=50)),
                ('ev_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_joinus',
            fields=[
                ('hj_id', models.AutoField(primary_key=True, serialize=False)),
                ('Home_joinus_name', models.CharField(max_length=50)),
                ('Home_joinus_phone', models.IntegerField()),
                ('Home_joinus_email', models.EmailField(max_length=30)),
                ('Home_joinus_location', models.CharField(max_length=100)),
                ('Home_joinus_desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Home_monthlyupdate',
            fields=[
                ('hmu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Home_joinus_email', models.EmailField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Home_recentventures',
            fields=[
                ('hrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Home_recentventures_caption', models.CharField(max_length=50)),
                ('Home_recentventures_desc', models.TextField(max_length=200)),
                ('Home_recentventures_date', models.DateField(default=datetime.datetime.now)),
                ('Home_recentventures_image', models.ImageField(upload_to='Homerecentventures_image')),
            ],
        ),
        migrations.CreateModel(
            name='Home_slider',
            fields=[
                ('hs_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Homeslider_desc', models.TextField(max_length=100)),
                ('Homeslider_link', models.URLField()),
                ('Homeslider_image', models.ImageField(upload_to='Homeslider_image')),
            ],
        ),
        migrations.CreateModel(
            name='Home_testimonials',
            fields=[
                ('ht_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Home_testimonials_designation', models.CharField(max_length=50)),
                ('Home_testimonials_desc', models.TextField(max_length=210)),
                ('Home_testimonials_date', models.DateField(default=datetime.datetime.now)),
                ('Home_testimonials_image', models.ImageField(upload_to='Hometestimonials_image')),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=39)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Male', max_length=50)),
                ('wp_number', models.CharField(max_length=15)),
                ('ph_number', models.CharField(max_length=15)),
                ('blood_gp', models.CharField(max_length=10)),
                ('Adress', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('facebook', 'facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('youtube', 'youtube'), ('linkdiln', 'linkdiln'), ('friends', 'friends'), ('Other', 'Other'), ('Own', 'Own')], default='whatsapp', max_length=50)),
                ('refferer', models.CharField(default='None', max_length=250)),
                ('hg_education', models.CharField(max_length=30)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Other', 'Other')], default='Student', max_length=50)),
                ('org_name', models.CharField(default='None', max_length=100)),
                ('hobbyskill', models.CharField(default='None', max_length=300)),
                ('soc_link', models.URLField()),
                ('past_ngo', models.CharField(default='None', max_length=100)),
                ('query', models.TextField(default='None', max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
