# Generated by Django 3.0.8 on 2021-09-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ev_time',
        ),
    ]
