# Generated by Django 3.0.8 on 2021-09-03 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_ev_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ev_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='ev_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
