# Generated by Django 3.0.8 on 2021-09-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210903_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_volunteer',
            fields=[
                ('av_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Aboutvolunteer_desc', models.TextField(max_length=50)),
                ('Aboutvolunteer_link', models.URLField()),
                ('Aboutvolunteer_image', models.ImageField(upload_to='Aboutvolunteer_image')),
                ('volunteer_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='ev_status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Upcoming', max_length=50),
        ),
    ]
