# Generated by Django 3.0.8 on 2021-09-04 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210904_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_desc', models.TextField(max_length=700)),
                ('pr_about', models.TextField(max_length=700)),
                ('pr_image1', models.ImageField(upload_to='Project_image')),
                ('pr_image2', models.ImageField(upload_to='Project_image')),
                ('pr_image3', models.ImageField(upload_to='Project_image')),
                ('pr_statisticksimg', models.ImageField(upload_to='Project_image')),
                ('pr_date', models.DateField(default=django.utils.timezone.now)),
                ('pr_time', models.TimeField(default=django.utils.timezone.now)),
                ('pr_cat', models.CharField(choices=[('Education', 'Education'), ('health & care', 'health & care'), ('environment', 'environment'), ('women empowerment', 'women empowerment'), ('coordination project', 'coordination project'), ('innovation part', 'innovation part'), ('Other', 'Other')], default='Education', max_length=50)),
                ('pr_mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=50)),
                ('pr_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Upcoming', max_length=50)),
                ('pr_link', models.URLField(default='https://sattvicsoul.org/')),
            ],
        ),
    ]
