# Generated by Django 3.0.8 on 2021-09-04 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_recentventures',
            fields=[
                ('prv_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Project_recentventures_cat', models.CharField(choices=[('Education', 'Education'), ('health & care', 'health & care'), ('environment', 'environment'), ('women empowerment', 'women empowerment'), ('coordination project', 'coordination project'), ('innovation part', 'innovation part'), ('Other', 'Other')], default='Education', max_length=50)),
                ('Project_recentventures_caption', models.CharField(max_length=50)),
                ('Project_recentventures_desc', models.TextField(max_length=200)),
                ('Project_recentventures_date', models.DateField(default=datetime.datetime.now)),
                ('Project_recentventures_image', models.ImageField(upload_to='Projectrecentventures_image')),
            ],
        ),
        migrations.CreateModel(
            name='Project_slider',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Projectslider_cat', models.CharField(choices=[('Education', 'Education'), ('health & care', 'health & care'), ('environment', 'environment'), ('women empowerment', 'women empowerment'), ('coordination project', 'coordination project'), ('innovation part', 'innovation part'), ('Other', 'Other')], default='Education', max_length=50)),
                ('Projectslider_desc', models.TextField(max_length=100)),
                ('Projectslider_link', models.URLField()),
                ('Projectslider_image', models.ImageField(upload_to='Projectslider_image')),
            ],
        ),
    ]
