# Generated by Django 3.2.3 on 2022-01-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_recentventures_project_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_testimonials',
            name='verification',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], default='Not Accepted', max_length=50),
        ),
    ]
